spring:
  datasource:
    url: ${datasource.url}?createDatabaseIfNotExist=true
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver