spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    drop-first: true

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false