spring:
  config:
    activate:
      on-profile: test

  liquibase:
    enabled: true
    contexts: test

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:bankapp
    username: sa
    password: sa

  jpa:
    open-in-view: false
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

  liquibase:
    enabled: true

  jpa:
    open-in-view: false